version: 0.0
Resources:
  - TargetService:
      Type: AWS::ECS::Service
      Properties:
        TaskDefinition: "<TASK_DEFINITION>"
        LoadBalancerInfo:
          ContainerName: "sample-website"
          ContainerPort: 80
# Optional properties
        PlatformVersion: "LATEST"
        NetworkConfiguration:
            AwsvpcConfiguration:
              Subnets: ["subnet-0364dea17b088aad0", "subnet-0e07a404d5a223aed","subnet-048d19a97fbea0857"]
              SecurityGroups: ["sg-0d8661f27abeab2f4"]
              AssignPublicIp: "DISABLED"